services:
  postgres:
    image: postgres:latest
    container_name: dog-api-production-ready-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dog_api_production_ready_db
    volumes:
      - postgres:/var/lib/postgresql
    ports:
      - "5433:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d dog_api_production_ready_db" ]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  postgres:
